{
 "title": "Backend Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(back_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 6 },
   "targets": [
    {
     "expr": "sum by (path) (rate(back_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(back_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "sum(back_http_requests_total)" }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(back_http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}