services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transcendence"]
      interval: 3s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GO_SERVICE_HOST: 0.0.0.0
      GO_SERVICE_PORT: 8080

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: transcendence
      DB_SSLMODE: disable
      DB_TIMEZONE: Europe/Madrid
    ports:
      - "8080:8080"

volumes:
  pgdata:
