filebeat.inputs:
  - type: filestream
    id: default-filestream
    paths:
      - /usr/share/filebeat/ingest_data/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata: ~

setup.kibana:
  host: "http://kibana:5601"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.logstash:
  hosts: ["logstash:5044"]