filebeat.inputs:
  - type: filestream
    id: go-backend-filestream
    enabled: true
    paths:
      - /usr/share/filebeat/ingest_data/*.log
    
    #parsers:
    #  - ndjson:
    #      keys_under_root: true
    #      overwrite_keys: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

setup.kibana:
  host: "https://kibana:5601"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.verification_mode: "none" 

output.logstash:
  hosts: ["logstash:5044"]