FROM docker.io/library/golang:1.26.5-alpine

WORKDIR /app

RUN apk add --no-cache git && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /dev/null ./cmd/api

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
