# TODO - Revisar configuración de Prometheus, revisar que es necesario implementar y configurar para el proyecto
# TODO - Definir que version de Prometheus se va a usar, revisar compatibilidad con Grafana
FROM prom/prometheus:latest

COPY prometheus.yml /etc/prometheus/prometheus.yml