# TODO - Revisar configuración de Grafana, revisar que es necesario implementar y configurar para el proyecto
# TODO - Definir que version de Grafana se va a usar, revisar compatibilidad con Prometheus
FROM grafana/grafana:latest

COPY datasources/datasources.yml /etc/grafana/provisioning/datasources/