apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # TODO - Configuración base, revisar subject para ver que es necesario implementar