import { Footer2FA, OtpInput } from "@components/TwoFactorUI"
import "../styles/pages/_authPages.scss"
import { useState } from "react"
import { Modal } from "@components/Modal"
import { Login2FA, getAuthenticatedUser } from "api/Login"
import { useAuth as useUserAuth } from "context/AuthContext"
import { useAuth as useRouterAuth } from "@components/auth-router/AuthContext"

// TODO - Mirar si es posible no hacer esta página intermedia y abrir la modal en /login

export const Login2fa = () => {
	const { refreshUser } = useUserAuth();
	const { refreshAuth } = useRouterAuth()
	const [otpCode, setOtpCode] = useState<string[]>(Array(6).fill(""));
	const isComplete = otpCode.every((d) => d !== "" && /\d/.test(d));
	const [show2FA, setShow2FA] = useState(true);

	const handleVerify2FA = async () => {
		if (!isComplete) return;

		try {
			await Login2FA(otpCode.join(""));
			await refreshAuth();
			await refreshUser();
			const data = await getAuthenticatedUser();
			setShow2FA(false);

			const login = data.user?.login;
			setShow2FA(false);
			if (login) {
            	window.location.href = (`/app/profile/${login}`);
				return;
			}
			window.location.href = "/app";
		} catch (err: any) {
			alert(err.message);
		}
	};

	return (
		<Modal
			open={show2FA}
			onClose={() => setShow2FA(false)}
			onSubmit={handleVerify2FA}
			submitDisabled={!isComplete}
			title="2FA Verification"
		>
			<p className="modal__content">
				To complete the login, enter the 2FA verification code generated by your authentication app.
			</p>
			<OtpInput onChange={setOtpCode} />
			<Footer2FA
				onClose={() => setShow2FA(false)}
				onVerify={handleVerify2FA}
				disabled={!isComplete}
			/>
		</Modal>
	)
}