input {
  file {
    mode => "tail"
    path => "/usr/share/logstash/ingest_data/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
  }
  

  stdout { 
    codec => rubydebug 
  }
}