name: tests

on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Environment File
        env:
          MY_SECRETS: ${{ secrets.ACTIONS_SECRETS }}
        run: |
          cat <<EOF > .env
          REDIS_PORT=6379
          REDIS_HOST=redis
          REDIS_PASSWORD=redispass
          ENV=local
          BACKEND_PORT=8080
          GO_SERVICE_HOST=0.0.0.0
          GO_SERVICE_PORT=8080
          FRONTEND_PORT=3000
          DB_HOST=postgres
          DB_PORT=5432
          DB_NAME=transcendence
          DB_USER=postgres
          DB_PASSWORD=postgrespass
          DB_SSLMODE=disable
          DB_TIMEZONE=Europe/Madrid
          PGADMIN_PORT=5050
          JWT_SECRET=uwu-super-mega-secret-for-jwt-auth
          JWT_EXPIRATION=86400
          PUBLIC_API_URL=https://localhost:6969/api/v1
          ISSUER_2FA=Tuentifour
          EXPIRATION_2FA=300
          NGINX_HOST=localhost
          NGINX_HTTP_PORT=1312
          NGINX_HTTPS_PORT=6969
          ENCRYPTION_KEY=c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2
          LICENSE=basic
          PGADMIN_DEFAULT_EMAIL=admin@admin.com
          PGADMIN_DEFAULT_PASSWORD=admin123
          PROJECT_NAME=ft_transcendence
          GO_ALLOWED_URLS=https://localhost:6969
          OAUTH42_CLIENT_ID=u-s4t2ud-57171ab2dde0c79802a8a9c94cc45db0e12e55ceea450c8191e4e7e54f2f1b35
          OAUTH42_CLIENT_SECRET=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
          OAUTH42_REDIRECT_URI=https://localhost/api/v1/auth/42/callback
          EOF

      - name: Install dependencies
        run: |
          make -C tests config

      - name: Run app
        run: |
          make dev-min-demon
          timeout 600s bash -c 'until curl -sk --connect-timeout 2 --max-time 10 http://localhost:8080/health; do sleep 3; done'
      - name: Debug de contenedores si falla
        if: failure()
        run: |
          docker compose -f docker-compose.dev.min.yml ps -a || true
          echo "=== LOGS BACKEND ==="
          docker logs ft_transcendence-backend-1 || true
          echo "=== LOGS REDIS ==="
          docker logs ft_transcendence-redis-1 || true
          echo "=== LOGS POSTGRES ==="
          docker logs ft_transcendence-postgres-1 || true

      - name: Run Tests
        run: make -C tests
