name: tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Environment File
        env:
          MY_SECRETS: ${{ secrets.ACTIONS_SECRETS }}
        run: |
          cat <<EOF > .env
          REDIS_PORT=6379
          ENV=local
          BACKEND_PORT=8080
          GO_SERVICE_HOST=0.0.0.0
          GO_SERVICE_PORT=8080
          FRONTEND_PORT=3000
          DB_PORT=5432
          DB_SSLMODE=disable
          DB_TIMEZONE=Europe/Madrid
          PGADMIN_PORT=5050
          JWT_EXPIRATION=86400
          GO_ALLOWED_URLS=
          ISSUER_2FA=Tuentifour
          EXPIRATION_2FA=300
          $MY_SECRETS
          EOF

      - name: Install dependencies
        run: |
          make -C tests config

      - name: delete old version
        run: |
          make full-remove

      - name: Run app
        run: |
          make
          timeout 120s bash -c 'until curl -s -k http://localhost:8080/api/v1/test; do sleep 2; done' || true
      # - name: Ver logs de Postgres si el arranque falla
      #   if: failure()
      #   run: |
      #     echo "LOGS DE POSTGRES"
      #     docker logs ft_transcendence-postgres-1 || true
      #     echo "ESTADO DE LOS CONTENEDORES"
      #     docker ps -a

      - name: Run Tests
        run: make -C tests
